canadianparks/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main_app.urls")),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    path("national-parks/", views.national_parks_index, name="national_parks_index"),
    path("national-parks/<int:national_park_id>/", views.national_parks_detail, 
    name="national_parks_detail"),
    path("national_parks_create/", views.NationalParkCreate.as_view(), name="national_parks_create"),
    path("national_parks/<int:pk>/update/", views.NationalParkUpdate.as_view(), name="national_parks_update"),
    path("national_parks/<int:pk>/delete/", views.NationalParkDelete.as_view(), name="national_parks_delete"),
    path("national_parks/<int:national_park_id>/add_trail/", views.add_trail, name="add_trail"),
]

nationalparks/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main_app.urls")),
]

main_app/models.py
from django.db import models
from django.urls import reverse

DIFFICULTIES = (
    ("E", "Easy"),
    ("M", "Moderate"),
    ("H", "Hard")
)

# Create your models here.
class National_park(models.Model):
    name = models.CharField(max_length=100)
    province = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    description = models.TextField(max_length=250)

    # Changing this instance method does not impact the database
    # Therefore, no makemigrations is necessary
    def __str__(self):
        return f"{self.name} ({self.id})"
    
    def get_absolute_url(self):
        return reverse("national_parks_detail", kwargs={"national_park_id": self.id})
    
class Trail(models.Model):
    name = models.CharField(max_length=100)
    difficulty = models.CharField(
        max_length=1,
        choices=DIFFICULTIES,
        default=DIFFICULTIES[1][0]
    )
    distance = models.FloatField("Trail Distance")
    national_park = models.ForeignKey(
        National_park,
        on_delete=models.CASCADE
    )
    def __str__(self):
        return f"{self.name} | {self.distance} km | difficulty: {self.get_difficulty_display()}"

main_app/forms.py
from django.forms import ModelForm
from .models import Trail

class TrailForm(ModelForm):
    class Meta:
        model = Trail
        fields = ["name", "distance", "difficulty"]

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import National_park
from .forms import TrailForm


# baby step - usually a model is used to store data

# Create your views here.
def home(request):
    return render(request, "home.html")

def about(request):
    return render(request, "about.html")

def national_parks_index(request):
    national_parks = National_park.objects.all().order_by("name")
    return render(request, "national_parks/index.html", {
        "national_parks": national_parks
    })

def national_parks_detail(request, national_park_id):
    national_park = National_park.objects.get(id=national_park_id)
    trail_form = TrailForm()
    return render(request, "national_parks/detail.html", {
        "national_park": national_park,
        "trail_form": trail_form
    })

class NationalParkCreate(CreateView):
    model = National_park
    fields = "__all__"
    # success_url = "/national_parks"

class NationalParkUpdate(UpdateView):
    model = National_park
    fields = ["province", "city", "description"]

class NationalParkDelete(DeleteView):
    model = National_park
    success_url = "/national-parks"

def add_trail(request, national_park_id):
    form = TrailForm(request.POST)
    if form.is_valid():
        new_trail = form.save(commit=False)
        new_trail.national_park_id = national_park_id
        new_trail.save()
    return redirect("national_parks_detail", national_park_id=national_park_id)

main_app/templates/about.html
{% extends "base.html" %}

{% block content %}

    <h1>About</h1>
    <hr>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Canadian Parks</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;Home</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'national_parks_create' %}">Add a National Park</a></li>
          <li><a href="{% url 'national_parks_index' %}">National Parks</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2021 Cat Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>National Parks</title>
</head>
<body>
    <h1>Home</h1>
</body>
</html>

main_app/templates/main_app/national_park_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete National Park</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'national_parks_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/national_park_form.html
{% extends "base.html" %}

{% block content %}

{% if object %}
    <h1>Edit <span class="teal-text">{{ object.name }}</span></h1>
{% else %}
    <h1>Add a National Park</h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="POST">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
        <!-- Render the inputs inside of <tr>s & <td>s -->
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
</form>

{% endblock %}

main_app/templates/national_parks/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Canadian National Parks</h1>
<hr>

<div class="card">
    <div class="card-content">
        <span class="card-title">{{ national_park.name }}</span>
        <p>Province: {{ national_park.province }}</p>
        <p>City: {{ national_park.city }}</p>
        <p>Description: {{ national_park.description|linebreaks }}</p>
        <!-- {% if cat.age > 0 %}
        <p>Age: {{ cat.age }}</p>
        {% else %}
        <p>Age: Kitten</p>
        {% endif %} -->
    </div>
    <div class="card-action">
        <a href="{% url 'national_parks_update' national_park.id %}">Edit</a>
        <a href="{% url 'national_parks_delete' national_park.id %}">Delete</a>
    </div>
    <div class="col s6">
        <form method="POST" action="{% url 'add_trail' national_park.id %}">
            {% csrf_token %}
            <!-- Render the inputs -->
            {{ trail_form.as_p }}
            <input type="submit" class="btn" value="Add Trail">
        </form>
        <table class="striped">
        <thead>
            <tr><th>Name</th><th>Difficulty</th><th>Distance</th></tr>
        </thead>
        <h4>Park Trails</h4>
        <tbody>
            {% for trail in national_park.trail_set.all %}
            <tr>
                <td>{{trail.name}}</td>
                <td>{{trail.get_difficulty_display}}</td>
                <td>{{ trail.distance }}</td>
            </tr>
            {% endfor %}
        </tbody>
        </table>
    </div>
</div>

<script>
    const selectEl = document.getElementById("id_difficulty");
    M.FormSelect.init(selectEl)
</script>

{% endblock %}

main_app/templates/national_parks/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Canadian National Parks</h1>
<hr>

{% for national_park in national_parks %}
    <div class="card">
        <a href="{% url 'national_parks_detail' national_park.id %}">
            <div class="card-content">
                <span class="card-title">{{ national_park.name }}</span>
                <p>Province: {{ national_park.province }}</p>
                <p>City: {{ national_park.city }}</p>
                <!-- {% if cat.age > 0 %}
                <p>Age: {{ cat.age }}</p>
                {% else %}
                <p>Age: Kitten</p>
                {% endif %} -->
            </div>
        </a>
    </div>
{% endfor %}

{% endblock %}